travis:
  secure:
    BINSTAR_TOKEN: MVRtZHlKEJ0B+JxH3JGxRo6Ws5wreDPJhPr98PFmB5/Erds/uuu96+yE+xDHgTeiX4L9sfTZxd9S0Ji/tVnklLbfI5Sereiy7gz2zG9MTkL2aoVGy8U5VlR6uT3lsMo1JxuuvGku7jsatH3ZmrIy8iZo/r1AhTPVffIG0Km1xxFj4oiy5i8Um5qUkLCMOAQC97bmWEzQxRCuSvw2XwNUjvbsAa09DE9PBU8h5huKR+oXfmUAuHG/pDkD91r09Dj/T/6dxuDHVmWyrLnw7ll0cMKGK6FDuRJ4G3grTzwzA0VA12KYmcTkZUKUMb9zEH1r8MXUEcz2YwkdXHHfRJE0eGze0tkymvlHZc2cX01jmAe1+2HJfDjc6Y7QhVL3TbKUf12mj99jTf4RK0T9t47wyQSdteRova3KCbsXRGFyLwJgTnPtSpOalltlkkpcLDctwJPz9Xcg1U6+7+ytGilRHktigMOIgfuuUbQi0BvpwbewQDllfzBLafjesdYodzZVAYKnIm4+//1mgB0YCZjIRQ2rF8P5EykUCvFlFcEbYdB2iktEmyUfiwSz+hcdv2e+MsrfXysHLN4/C7mCMlUdIhwa/uYguldXY4iIfdvEJ8p+l83qNRSsYexfnK6kHEZCQyT/kz/Bi/a3N47ALK7mP+PwEb6HoCMjqsi5g6kvrQs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
